export const images = [
  require('../../assets/img1.png'),
  require('../../assets/img2.png'),
  require('../../assets/img3.png'),
  require('../../assets/img4.png'),
  require('../../assets/img5.png'),
  require('../../assets/img6.png'),
  require('../../assets/img7.png'),
  require('../../assets/img8.png'),
  require('../../assets/img9.png'),
  require('../../assets/img10.png'),
];

export const products = [
  {
    id: 1,
    title: 'Product 1',
    image: require('../../assets/img1.png'),
    description: 'Description for Product 1',
    quantity: 10,
    weight: '100g',
    dimensions: '10x10x10 cm',
    SKU: 'SKU001',
    price: '$10',
    category: 'Category 1',
  },
  {
    id: 2,
    title: 'Product 2',
    image: require('../../assets/img2.png'),
    description: 'Description for Product 2',
    quantity: 15,
    weight: '150g',
    dimensions: '15x15x15 cm',
    SKU: 'SKU002',
    price: '$15',
    category: 'Category 2',
  },
  {
    id: 3,
    title: 'Product 3',
    image: require('../../assets/img3.png'),
    description: 'Description for Product 3',
    quantity: 15,
    weight: '150g',
    dimensions: '15x15x15 cm',
    SKU: 'SKU002',
    price: '$15',
    category: 'Category 3',
  },
  {
    id: 4,
    title: 'Product 4',
    image: require('../../assets/img4.png'),
    description: 'Description for Product 4',
    quantity: 15,
    weight: '150g',
    dimensions: '15x15x15 cm',
    SKU: 'SKU002',
    price: '$15',
    category: 'Category 4',
  },
  {
    id: 5,
    title: 'Product 5',
    image: require('../../assets/img5.png'),
    description: 'Description for Product 5',
    quantity: 15,
    weight: '150g',
    dimensions: '15x15x15 cm',
    SKU: 'SKU002',
    price: '$15',
    category: 'Category 5',
  },
  {
    id: 6,
    title: 'Product 6',
    image: require('../../assets/img6.png'),
    description: 'Description for Product 6',
    quantity: 15,
    weight: '150g',
    dimensions: '15x15x15 cm',
    SKU: 'SKU002',
    price: '$15',
    category: 'Category 6',
  },
];

export const categories = [
  {
    id: 1,
    title: 'Category 1',
    description: 'Description for Category 1',
    image: require('../../assets/img1.png'),
  },
  {
    id: 2,
    title: 'Category 2',
    description: 'Description for Category 2',
    image: require('../../assets/img2.png'),
  },
  {
    id: 3,
    title: 'Category 3',
    description: 'Description for Category 3',
    image: require('../../assets/img3.png'),
  },
  {
    id: 4,
    title: 'Category 4',
    description: 'Description for Category 4',
    image: require('../../assets/img4.png'),
  },
  {
    id: 5,
    title: 'Category 5',
    description: 'Description for Category 5',
    image: require('../../assets/img5.png'),
  },
  {
    id: 6,
    title: 'Category 6',
    description: 'Description for Category 6',
    image: require('../../assets/img6.png'),
  },
  {
    id: 7,
    title: 'Category 7',
    description: 'Description for Category 7',
    image: require('../../assets/img7.png'),
  },
  {
    id: 8,
    title: 'Category 8',
    description: 'Description for Category 8',
    image: require('../../assets/img8.png'),
  },
  {
    id: 9,
    title: 'Category 9',
    description: 'Description for Category 9',
    image: require('../../assets/img9.png'),
  },
  {
    id: 10,
    title: 'Category 10',
    description: 'Description for Category 10',
    image: require('../../assets/img10.png'),
  },
];
